### ISSUE TITLE
6.3.23 openssl error

### ISSUE THREAD

**Issue by imperatorx** [Doxense/foundationdb-windows-build#2]
Hi, do you happen to know what broke the 6.3.23 build? I can build the 7.0.0 no problem, but the 6.3.23 complains:  
fatal error : 'openssl/sha.h' file not found

If I chockolatey install openssl and manually copy the header files, it fails much later not finding the compiled libcrypto files. The strange thing is the configure script is able to find the OpenSSL install.

**Comment by moulmahdi** [comment]
TLS support is disabled for Windows, so cmake will not try to find it and then add the underlying include directory to the solution (see TLS section on cmake/FDBComponents.cmake). A pull request was opened to fix this: https://github.com/apple/foundationdb/pull/6193. Of course, you still need to install OpenSSL.
Also, there is a WIP to update the Windows docker image including OpenSSL.

**Comment by imperatorx** [comment]
thank you, it worked
